[PHP]
memory_limit = 512M
max_execution_time = 30
upload_max_filesize = 20M
post_max_size = 20M

[Date]
date.timezone = Europe/Warsaw

[MySQL]
mysql.default_socket = /var/run/mysqld/mysqld.sock
pdo_mysql.default_socket = /var/run/mysqld/mysqld.sock

[MySQLi]
mysqli.default_socket = /var/run/mysqld/mysqld.sock